name: Deploy API Gateway to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true

    - name: Rename JAR for consistent deployment
      run: mv target/*.jar mifinca-backend-gateway.jar

    - name: Copy JAR to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER_NAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        source: "mifinca-backend-gateway.jar"
        target: ${{ secrets.SERVER_DEPLOY_PATH }}

    - name: Ejecutar script remoto para desplegar Gateway
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER_NAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          chmod +x /home/gabriel/scripts/mifinca-backend-gateway-deploy.sh
          /home/gabriel/scripts/mifinca-backend-gateway-deploy.sh
